apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  project: default
  source:
    path: app-template
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        replicaCount: 2
        name: http-echo
        image:
          name: mendhak/http-https-echo
          tag: 30
        configuration:
        - name: HTTP_PORT
          value: "80"