apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "insgress-test.com"
    http:
      paths:
      - path: /{{ .Values.name }}/
        pathType: Prefix  
        backend:
          service:
            name: {{ .Values.name }}
            port: 
              number: 80
